#!/usr/bin/env bash
set -euo pipefail

plugin_dir="wp-content/plugins/newsvoice-article-builder"
plugin_file="$plugin_dir/newsvoice-article-builder.php"
template_file="wp-content/themes/newsvoice/template-standard_article.php"
compose_file="docker-compose.yml"

test -f "$plugin_file" || {
	echo "Missing plugin file: $plugin_file" >&2
	exit 1
}

grep -q "Plugin Name: NewsVoice Article Builder" "$plugin_file"
grep -q "NewsVoice Artikelbyggare" "$plugin_file"
grep -q "add_meta_box" "$plugin_file"
grep -q "newsvoice_article_builder_render_meta_box" "$plugin_file"
grep -q "save_post" "$plugin_file"
grep -q "newsvoice_article_builder_save_post" "$plugin_file"
grep -q "wp_enqueue_media" "$plugin_file"
grep -q "add_menu_page" "$plugin_file"
grep -q "newsvoice_article_builder_render_admin_page" "$plugin_file"
grep -q "newsvoice_article_builder_handle_form_submit" "$plugin_file"
grep -q "newsvoice_article_builder_default_article" "$plugin_file"
grep -q "newsvoice_article_builder_default_asset_url" "$plugin_file"
grep -q "wp_dropdown_categories" "$plugin_file"
grep -q "newsvoice_article_category" "$plugin_file"
grep -q "wp_set_post_categories" "$plugin_file"
grep -q "template-standard_article.php" "$plugin_file"
grep -q "article_kicker" "$plugin_file"
grep -q "newsvoice_article_dek" "$plugin_file"
grep -q "newsvoice_article_ingress" "$plugin_file"
grep -q "nv-article-ingress" "$plugin_file"
grep -q "newsvoice_article_builder_split_ingress_from_content" "$plugin_file"
grep -q "newsvoice_article_builder_render_field_cards( \$post_id, \$defaults, 'header' )" "$plugin_file"
grep -q "newsvoice_article_builder_render_field_cards( \$post_id, \$defaults, 'end' )" "$plugin_file"
grep -q "newsvoice_hero_caption" "$plugin_file"
grep -q "newsvoice_sources" "$plugin_file"
grep -q "newsvoice_support_image_id" "$plugin_file"
grep -q "newsvoice_medialinq_image_id" "$plugin_file"
grep -q "newsvoice_banner_image_id" "$plugin_file"
grep -q "Israels och USA:s krig mot Iran" "$plugin_file"
grep -q "Iran-armada-1170x600.jpg" "$plugin_file"
grep -q "NVannons.png" "$plugin_file"
grep -q "kaffeannons.png" "$plugin_file"
grep -q "annonsera-i-newsvoice.jpg" "$plugin_file"
grep -q "newsvoice_support_image_url" "$plugin_file"
grep -q "newsvoice_medialinq_image_url" "$plugin_file"
grep -q "newsvoice_banner_image_url" "$plugin_file"
grep -q "newsvoice-article-builder-admin.js" "$plugin_file"
grep -q "newsvoice-article-builder-admin.css" "$plugin_file"

test -f "$plugin_dir/assets/js/newsvoice-article-builder-admin.js"
test -f "$plugin_dir/assets/css/newsvoice-article-builder-admin.css"

grep -q "wp.media" "$plugin_dir/assets/js/newsvoice-article-builder-admin.js"
grep -q "article-builder-preview" "$plugin_dir/assets/js/newsvoice-article-builder-admin.js"
grep -q "updateArticleHeroPreview" "$plugin_dir/assets/js/newsvoice-article-builder-admin.js"
grep -q "updateArticleAssetPreview" "$plugin_dir/assets/js/newsvoice-article-builder-admin.js"
grep -q "data-preview-output=\"body\"" "$plugin_file"
grep -q "data-preview-output=\"article_ingress\"" "$plugin_file"
grep -q "data-preview-output=\"sources\"" "$plugin_file"
grep -q "data-preview-output=\"support_image\"" "$plugin_file"
grep -q "data-preview-output=\"medialinq_image\"" "$plugin_file"
grep -q "data-preview-output=\"banner_image\"" "$plugin_file"
grep -q "data-preview-field" "$plugin_file"
grep -q "wp_editor" "$plugin_file"
grep -q "nv_article_content" "$plugin_file"
grep -q "'textarea_name'.*'post_content'" "$plugin_file"
grep -q "'media_buttons'.*false" "$plugin_file"
grep -q "'quicktags'.*false" "$plugin_file"
grep -q "bold italic removeformat" "$plugin_file"
grep -q "article-builder-preview__canvas" "$plugin_file"
grep -q "nv-article-builder-page__toolbar" "$plugin_file"
grep -q "nv-article-builder-save-top" "$plugin_file"
grep -q "article-end-section" "$plugin_file"
grep -q "article-author-card" "$plugin_file"
grep -q "article-builder-preview__article" "$plugin_dir/assets/css/newsvoice-article-builder-admin.css"
grep -q "article-builder-preview__canvas" "$plugin_dir/assets/css/newsvoice-article-builder-admin.css"
grep -q "nv-article-builder-page__toolbar" "$plugin_dir/assets/css/newsvoice-article-builder-admin.css"
grep -q "nv-article-builder-editor" "$plugin_dir/assets/css/newsvoice-article-builder-admin.css"
grep -q "justify-content: flex-end" "$plugin_dir/assets/css/newsvoice-article-builder-admin.css"
grep -q "grid-column: 2;" "$plugin_dir/assets/css/newsvoice-article-builder-admin.css"
grep -q "renderSourcesPreview" "$plugin_dir/assets/js/newsvoice-article-builder-admin.js"
grep -q "getArticleEditorContent" "$plugin_dir/assets/js/newsvoice-article-builder-admin.js"
grep -q "bindArticleEditorPreview" "$plugin_dir/assets/js/newsvoice-article-builder-admin.js"
grep -q "tinyMCE.get('nv_article_content')" "$plugin_dir/assets/js/newsvoice-article-builder-admin.js"
grep -q "article-sources" "$plugin_dir/assets/js/newsvoice-article-builder-admin.js"

grep -q "newsvoice_article_dek" "$template_file"
grep -q "newsvoice_article_ingress" "$template_file"
grep -q "article-ingress" "$template_file"
grep -q "newsvoice_hero_caption" "$template_file"
grep -q "newsvoice_sources" "$template_file"
grep -q "newsvoice_support_image_id" "$template_file"
grep -q "newsvoice_medialinq_image_id" "$template_file"
grep -q "newsvoice_banner_image_id" "$template_file"

grep -q "./wp-content/plugins/newsvoice-article-builder:/var/www/html/wp-content/plugins/newsvoice-article-builder" "$compose_file"
grep -q "wp plugin activate newsvoice-article-builder" "$compose_file"
