#!/usr/bin/env bash
set -euo pipefail

plugin_dir="wp-content/plugins/newsvoice-homepage-builder"
plugin_file="$plugin_dir/newsvoice-homepage-builder.php"
front_page="wp-content/themes/newsvoice/front-page.php"
theme_js="wp-content/themes/newsvoice/assets/js/theme.js"
functions_file="wp-content/themes/newsvoice/functions.php"
compose_file="docker-compose.yml"

test -f "$plugin_file" || {
	echo "Missing plugin file: $plugin_file" >&2
	exit 1
}

grep -q "Plugin Name: NewsVoice Homepage Builder" "$plugin_file"
grep -q "add_menu_page" "$plugin_file"
grep -q "toplevel_page_newsvoice-homepage-builder" "$plugin_file"
grep -q "register_setting" "$plugin_file"
grep -q "newsvoice_homepage_builder_settings_page" "$plugin_file"
grep -q "newsvoice_homepage_builder_get_settings" "$plugin_file"
grep -q "newsvoice_homepage_builder_default_asset_url" "$plugin_file"
grep -q "newsvoice_homepage_builder_default_sections" "$plugin_file"
grep -q "newsvoice_homepage_builder_render_article_grid" "$plugin_file"
grep -q "newsvoice_homepage_builder_render_ad_slot" "$plugin_file"
grep -q "newsvoice_homepage_builder_render_top_ad" "$plugin_file"
grep -q "wp_enqueue_media" "$plugin_file"
grep -q "newsvoice_homepage_builder_asset_version" "$plugin_file"
grep -q "filemtime" "$plugin_file"
grep -q "newsvoice_homepage_builder_article_choices" "$plugin_file"
grep -q "newsvoice_homepage_builder_article_choice_field" "$plugin_file"
grep -q "newsvoice-homepage-choice-modal" "$plugin_file"
grep -q "newsvoice-homepage-algo-modal" "$plugin_file"
grep -q "data-homepage-choice-field" "$plugin_file"
grep -q "Manuellt val" "$plugin_file"
grep -q "Algoritm" "$plugin_file"
grep -q "newsvoice-homepage-builder-admin.js" "$plugin_file"
grep -q "newsvoice-homepage-builder-admin.css" "$plugin_file"
grep -q "homepage-builder-preview" "$plugin_file"
grep -q "homepage-builder-preview__canvas" "$plugin_file"
grep -q "homepage-builder-preview__video" "$plugin_file"
grep -q "homepage-builder-preview__english" "$plugin_file"
grep -q "homepage-builder-preview__footer" "$plugin_file"
grep -q "Mediapartners" "$plugin_file"
grep -q "Video / NewsVoice TV" "$plugin_file"
grep -q "featured_post_id" "$plugin_file"
grep -q "top_grid_post_ids" "$plugin_file"
grep -q "sidebar_ads" "$plugin_file"
grep -q "top_ad" "$plugin_file"
grep -q "Iran-armada-1170x600.jpg" "$plugin_file"
grep -q "NVannons.png" "$plugin_file"
grep -q "PremiumVpn.png" "$plugin_file"
grep -q "newvoice-mullvad-vpn.png" "$plugin_file"
grep -q "image_url" "$plugin_file"

test -f "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
test -f "$plugin_dir/assets/css/newsvoice-homepage-builder-admin.css"
grep -q "wp.media" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "homepage-builder-preview" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "renderHomepagePreview" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "renderPreviewAd" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "homepage-preview-card" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "homepage-preview-section-card" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "homepage-builder-preview__playlist-item" "$plugin_dir/assets/css/newsvoice-homepage-builder-admin.css"
grep -q "must-watch-section" "$plugin_file"
grep -q "video-container" "$plugin_file"
grep -q "openChoiceModal" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "openAlgoModal" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "renderChoiceGallery" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "saveManualChoice" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "saveAlgoChoice" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "newsvoiceHomepageBuilder" "$plugin_dir/assets/js/newsvoice-homepage-builder-admin.js"
grep -q "min-width: 0" "$plugin_dir/assets/css/newsvoice-homepage-builder-admin.css"
grep -q "overflow: hidden" "$plugin_dir/assets/css/newsvoice-homepage-builder-admin.css"
grep -q "object-fit: contain" "$plugin_dir/assets/css/newsvoice-homepage-builder-admin.css"
grep -q "nv-home-builder-controls" "$plugin_file"
grep -q "nv-home-builder-preview-panel" "$plugin_file"
grep -q "grid-template-columns: repeat(2" "$plugin_dir/assets/css/newsvoice-homepage-builder-admin.css"
grep -q "data-homepage-preview-output" "$plugin_file"
grep -q "data-homepage-preview-ad" "$plugin_file"
grep -q "nv-featured-image-url" "$plugin_file"

grep -q "newsvoice_homepage_builder_render_front_page" "$front_page"
grep -q "newsvoice_homepage_builder_render_top_ad" "wp-content/themes/newsvoice/header.php"
grep -q "homeBuilderEnabled" "$functions_file"
grep -q "homeBuilderEnabled" "$theme_js"
grep -q "./wp-content/plugins/newsvoice-homepage-builder:/var/www/html/wp-content/plugins/newsvoice-homepage-builder" "$compose_file"
grep -q "wp plugin activate newsvoice-homepage-builder" "$compose_file"
